from .OutputModuleType import OutputModuleType
from .ConvSupersamplingModule import ConvSupersamplingModule
from .ResNetSupersamplingModule import ResNetSupersamplingModule
from .ResidualOutputModule import ResidualOutputModule